### ISSUE TITLE
测试手机

### ISSUE THREAD

**Issue by XiaomaG** [XiangyuTang/WifiRttScanT#2]
您好，请问使用什么手机测试的？我使用小米Mix2S，提示不支持FTM，是否需要刷机？刷什么镜像？谢谢

**Comment by XiangyuTang** [comment]
你好，我这边测试支持FTM的有红米note 9 pro, 红米k20 pro，如果你的手机不支持FTM可能只有换一台再试试，不需要刷机




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiangyuTang/WifiRttScanT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 上午9:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XiangyuTang/WifiRttScanT] 测试手机 (Issue #2)





 
您好，请问使用什么手机测试的？我使用小米Mix2S，提示不支持FTM，是否需要刷机？刷什么镜像？谢谢

**Comment by XiangyuTang** [comment]
另外支持FTM的手机和AP设备可参考（中英文界面的手机设备列表不同）：https://developer.android.google.cn/guide/topics/connectivity/wifi-rtt?hl=zh_cn 和https://developer.android.google.cn/guide/topics/connectivity/wifi-rtt
